[package]
name = "arm7tdmi"
version = "0.0.0"
authors = ["Juici <juicy66173@gmail.com>"]
description = "Library for emulating the ARM7TDMI CPU."
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
log = "0.4"
int-enum = { version = "0.4", features = ["convert"] }
