[package]
name = "rom"
version = "0.0.0"
authors = ["Juici <juicy66173@gmail.com>"]
description = "Library for loading ROMs."
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
log = "0.4"
byteorder = "1.4"
